# Generated by Django 3.0.7 on 2021-07-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='subcategory_images')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Icards.Add_category')),
            ],
        ),
    ]
