# Generated by Django 3.0.7 on 2021-07-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Icards', '0002_add_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_subcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='add_subcategory',
            name='main_category',
        ),
    ]
