# Generated by Django 3.0.7 on 2021-07-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icards', '0003_auto_20210706_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_subcategory',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Icards.Add_category'),
            preserve_default=False,
        ),
    ]
