# Generated by Django 3.0.7 on 2021-07-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icards', '0004_add_subcategory_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_subcategory',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='subcategory_images'),
        ),
    ]
