# Generated by Django 3.0.7 on 2021-07-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icards', '0005_add_subcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_subcategory',
            old_name='image',
            new_name='subcategory_image',
        ),
        migrations.CreateModel(
            name='Add_icard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('title_image', models.ImageField(default='default.jpg', upload_to='title_images')),
                ('subcategory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Icards.Add_category')),
            ],
        ),
    ]
