# Generated by Django 3.0.7 on 2021-07-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icards', '0006_auto_20210706_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_icard',
            name='subcategory_name',
        ),
        migrations.AddField(
            model_name='add_icard',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Icards.Add_subcategory'),
            preserve_default=False,
        ),
    ]
