# Generated by Django 3.0.7 on 2021-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icards', '0007_auto_20210706_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
